---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/certidoes":
    get:
      summary: Consulta certidões
      tags:
      - Certidões
      parameters:
      - name: cpf_cnpj
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Certidões encontradas
          content:
            application/json:
              schema:
                type: object
                properties:
                  cpf_cnpj:
                    type: string
                  certidoes:
                    type: array
                    items:
                      type: object
                      properties:
                        tipo:
                          type: string
                        status:
                          type: string
                        conteudo_base64:
                          type: string
  "/credores":
    post:
      summary: Cria um credor
      tags:
      - Credores
      parameters: []
      responses:
        '201':
          description: Credor criado
          content:
            application/json:
              examples:
                success:
                  value:
                    id: 1
                    nome: João Silva
                    cpf_cnpj: 123.456.789-09
                    email: example@email.com
                    telefone: '12345678901'
                    created_at: '2025-05-15T20:24:24.773Z'
                    updated_at: '2025-05-15T20:24:24.773Z'
                    precatorios:
                    - id: 2
                      numero_precatorio: numero002
                      valor_nominal: '200.0'
                      foro: foro tal
                      data_publicacao: '2025-05-15'
        '422':
          description: Dados inválidos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                cpf_cnpj:
                  type: string
                email:
                  type: string
                telefone:
                  type: string
                precatorio:
                  type: object
                  properties:
                    numero_precatorio:
                      type: string
                    valor_nominal:
                      type: number
                    foro:
                      type: string
                    data_publicacao:
                      type: string
                      format: date
              required:
              - nome
              - cpf_cnpj
  "/credores/{id}":
    get:
      summary: Exibe um credor
      tags:
      - Credores
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Credor encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nome:
                    type: string
                  precatorios:
                    type: array
                  documentos_pessoais:
                    type: array
                  certidoes:
                    type: array
  "/credores/{id}/documentos":
    post:
      summary: Faz upload de documento pessoal
      tags:
      - Documentos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Documento salvo
        '422':
          description: Erro de validação
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: file
        required: true
servers:
- url: http://{defaultHost}:{port}
  variables:
    defaultHost:
      default: localhost
    port:
      default: '3000'
