default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  port: 5432
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: mercatorio_backend_development

test:
  <<: *default
  database: mercatorio_backend_test

production:
  primary: &primary_production
    <<: *default
    database: mercatorio_backend_production
    username: mercatorio_backend
    password: <%= ENV["MERCATORIO_BACKEND_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: mercatorio_backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mercatorio_backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mercatorio_backend_production_cable
    migrations_paths: db/cable_migrate
